version: '3'
services: 
  web:
    build: 
    # define where we want all files and folders for this image pulled from
      context: .
      dockerfile: Dockerfile.dev
    ports: 
     - "3000:3000"
    volumes: 
    # bookmark node_modules
    - /app/node_modules
    # map rest of files
    - .:/app
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]